export default Object.freeze({
  // 물품 판매 상태 상수값
  ITEM_STATE_ONSALE: "ITEM_ONSALE",
  ITEM_STATE_PURCHASECOMPLETE: "ITEM_PURCHASECOMPLETE",
  ITEM_STATE_ONDELIVERY_REQ: "ITEM_ONDELIVERY_REQ",
  ITEM_STATE_ONDELIVERY: "ITEM_ONDELIVERY",
  ITEM_STATE_ONDELIVERYCOMPLETE_REQ: "ITEM_ONDELIVERYCOMPLETE_REQ",
  ITEM_STATE_DELIVERYCOMPLETE: "ITEM_DELIVERYCOMPLETE",
  ITEM_STATE_PURCHASECONFIRMED: "ITEM_PURCHASECONFIRMED",
  ITEM_STATE_PURCHASEDENIED: "ITEM_PURCHASEDENIED",
  ITEM_STATE_CYCLEFINISHED: "ITEM_CYCLEFINISHED",
});
